### ISSUE TITLE
Sketch 50 does not show all paddy 2 options in the panel 

### ISSUE THREAD

**Issue by AnnaMBojarowicz** [DWilliames/paddy2-beta#13]
Hey there, Sketch ver. 50 does not show all padding option in the panel
![screen shot 2018-05-11 at 15 49 54](https://user-images.githubusercontent.com/37807273/39927696-61d6362e-5533-11e8-90b5-dca8533e1884.png)

**Comment by DWilliames** [comment]
Thanks @AnnaMBojarowicz.
I just released a new version of the beta that should support Sketch 50 a bit better.

However, in your case, 'padding' won't show in the inspector because you have a Group selected. For it to show; you must select the shape layer itself.

Let me know how you go 👍

**Comment by DWilliames** [comment]
Thanks @AnnaMBojarowicz!!
It's great to feel the love from all around the world ❤️
