### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by aparajita** [DWilliames/paddy2-beta#14]
Paddy2 is looking great! Just a few small UI observations that would improve the experience:

- Stack alignment and "Ignore for spaciing / padding" appear **above** "Stack layers", which is counter-intuitive. "Stack layers" is effectively a section header, so we expect everything related to that to appear below, as it does with every other inspector section in Sketch.

- It would be nice if your section name colors matched Sketch's (Fills, Borders, etc.). Sketch uses #515151.

- Currently we cannot remove padding without first unchecking the padding, then we can click the trash can. Unchecking first is redundant, we know we want to turn that padding off because we are about to delete it.

- The stack alignment icons could be stronger. I'd be happy to submit some if you're interested.

**Comment by DWilliames** [comment]
Really great points here @aparajita. Thanks.

* Makes sense. Should be an easy fix 👍 

* I realised I matched the heading colour when I had 'Midnight' installed with the 'Lark' theme 🙊 

* I was following the pattern of the other styles here – e.g. Fills, borders, Shadows. Where after unchecking, the 'trash bin' appears. I feel like in some cases the checkbox made it easy to temporarily disable the padding. In some cases I've wanted to 'freeze' the padding, and not auto-update for a bit while I'm really dunging around the layout. Then I can 'unfreeze' it when I'm ready for it to auto-adjust again. But perhaps maybe I just have the bin there always?

* Yeah I agree — If you're wanting to take a stab at it. That would be great. Here's my file of what I've used: [paddy_icons.zip](https://github.com/DWilliames/paddy2-beta/files/2000187/paddy_icons.zip)

**Comment by aparajita** [comment]
As for unchecking padding, I wasn't suggesting you should remove the checkbox, only that the trash can should always be available. It's true that Sketch requires unchecking fills, shadows, etc. before deleting them, but honestly it makes no sense from a UX point of view, especially since you are able to drag a fill/shadow to delete it without first unchecking it. So in this case I think you're better off not following their example.

**Comment by aparajita** [comment]
I'll work on the icons, give me a few days.

Speaking of icons, it looks like the stack orientation icons are trying to display the words "Vertical" and "Horizontal", which of course don't fit into a 16px space and prevent the icons from being centered.

**Comment by Arroyodorado** [comment]
Also, making the stack-folder-icons a bit stronger would make them more useful. The white bars seem a bit too subtle to me.

Paddy 2 works great so far! Thanks for making this! 8-)

![folder-icons](https://user-images.githubusercontent.com/10092794/40063228-252720ee-585d-11e8-99bd-5d842afefe01.png)

**Comment by DWilliames** [comment]
Ah cool. Thanks @Arroyodorado. Great idea.

**Comment by aparajita** [comment]
Latest build is much better! Love the new alignment options! I recommend changing the wording from "Align group's layers" to "Group alignment". To be consistent with Sketch (and the rest of macOS), it should be a noun, not a verb, because the buttons represent state.

**Comment by DWilliames** [comment]
Hey @aparajita and @Arroyodorado.

I just released v0.3 which has all these changes included.
Let me know if you come across anymore issues.

@aparajita; let me know how you go with the 'alignment' icons. No rush. Maybe open a separate issue to include them when you get around to it 👍
