### ISSUE TITLE
Issues when removing padding

### ISSUE THREAD

**Issue by aparajita** [DWilliames/paddy2-beta#15]
Sketch 49, Paddy2 v0.2:

1. Select a background shape layer.
1. Click padding +.
1. Uncheck padding.
1. Delete padding.

Two issues occur:

- The Paddy icon is removed, but the normal layer icon does not appear.
- "Ignore for spacing / padding" is checked by itself.

**Comment by DWilliames** [comment]
Thanks again @aparajita! 
I'm able to reproduce this.

Cheers 👍

**Comment by DWilliames** [comment]
Hey @aparajita – this should be fixed in the v0.3 build 👍
