### ISSUE TITLE
Padding algorithm workes other way (comparing with paddy 1)

### ISSUE THREAD

**Issue by mikeozornin** [DWilliames/paddy2-beta#16]
In the new Paddy 2 padding algorithm workes not the same as paddy 1.

Paddy build: from https://github.com/DWilliames/paddy2-beta/issues/12#issuecomment-388759654
Sketch: 50 (54983)
The same file: https://sketch.cloud/s/drAvj

I use the following structure for button symbol:
**-add-state** with ignore padding
**button-text** (used for calculate symbol state)
**base-state** with padding

![image](https://user-images.githubusercontent.com/1744928/40011707-4396a9d4-57b1-11e8-901e-4c33e35e0737.png)

Paddy 1 works this one:
1. Select **button-text** layer — this will be the base for symbol size calculations.
2. Using padding from **button-text** paddy resize whole symbol to set **base-state** needed size.
3. Ignored layers were resized with the symbol resizing accorning to their resize options.

Paddy 2 fully ignore layer with - and they preserve their size.

How to reproduce:
1. Download and open file: https://sketch.cloud/s/drAvj
2. On the page „dev-docs“ find artboard „buttons 2.0“ and select any button and make text override.

Expected (paddy 1 work tihs way):
All layer are aligned:
![image](https://user-images.githubusercontent.com/1744928/40011596-f3b6d510-57b0-11e8-914d-ee1ced8d0c99.png)

Result:
Button base state is correct size, but the **add-layer** layer fully ignored and not resized.
![image](https://user-images.githubusercontent.com/1744928/40011379-5940dc56-57b0-11e8-94d4-00bdd55c97e6.png)

**-add-layer** layer is 1px bigger than **base-state** by all directions. This hack allow to make outer border. But it doesn't matter for this issue.
![image](https://user-images.githubusercontent.com/1744928/40011693-39622146-57b1-11e8-9886-bc39f81c98ff.png)

The second problem is that **add-state** layer is always positioned to point [0, 0]. Paddy 1 save its original [-1, -1] position.
 
What do you think? What is expected behavior?

**Comment by DWilliames** [comment]
Thanks @mikeozornin.
Yeah, that's an issue I'm still working through, and accidentally included some of the stuff I was working on in the Build I gave you in #12. Oops

Try this build in the meantime... [Paddy2.sketchplugin.zip](https://github.com/DWilliames/paddy2-beta/files/2007014/Paddy2.sketchplugin.zip)
It should still fix your original crash; as well as not including this weird symbol behaviour you described above.

**Comment by mikeozornin** [comment]
Goody!
Confirm no crashes and no strange resize behavior in this build.

Will try to use this version in everyday work.

Plugin icon 💚
