### ISSUE TITLE
Entering any character into the Paddy's fields crashes Sketch

### ISSUE THREAD

**Issue by richardsison** [DWilliames/paddy2-beta#18]
![image](https://user-images.githubusercontent.com/587608/40290126-77079672-5cff-11e8-878f-67a54875b236.png)

I tried entering "x" and a dash "-" to try and replicate the "ignore side" functionality in Paddy 1. Where you could type:

"Group Name [24 x x x]"

It just crashes Sketch for me.

**Comment by DWilliames** [comment]
Thanks Richard. 

In the new v0.3 build this should be fixed now.
In order to have no specified padding on an edge; you can now either enter 'x' or simply clear the field to 'none'. Let me no how go.

If it still crashes for you on the latest build; please re-open this issue.
