### ISSUE TITLE
Edit Padding on Multiple Items

### ISSUE THREAD

**Issue by nickm717** [DWilliames/paddy2-beta#20]
May be on the roadmap, but having the ability to edit the padding values of multiple layers at a time. Previously was able to do this in the layer panel with the Rename-It plugin and now that is no longer an option.

**Comment by DWilliames** [comment]
Thanks Nick.

I just released v0.3 of Paddy 2. This should allow editing the padding values on multiple layers at a time.

Let me know how it goes for you. If you find some issues with it; please open another Github 'issue;, with a more specific example 👍

**Comment by nickm717** [comment]
You are the man @DWilliames ! You have done such incredible work with this update. I will have to update my tutorial.
