### ISSUE TITLE
Collapse hidden views – Last/First in group unaffected

### ISSUE THREAD

**Issue by HendrikVdB** [DWilliames/paddy2-beta#26]
If I use the "Collapse hidden views" feature in a group it will only work with surrounded layers.

For example a group with 3 layers: Headline, Copy, Link.
Whenever I hide the Link or Headline layer the group doesn't resize, only the Copy layer affects the group.

This feature would be great for whenever you have a long stacked maingroup-subgroup list with a lot of subgroup variaties. (e.g. Link isn't part of every element)

**Comment by aparajita** [comment]
In other words, the first and last layers in a group, when hidden, do not affect the size of the group.

**Comment by DWilliames** [comment]
Great find @HendrikVdB!
This one turned out to be quite tricky to do surprisingly — but I think I cracked it. Will be included in v0.4 which will be out in the next day or 2.

**Comment by aparajita** [comment]
Fixed for me.

**Comment by DWilliames** [comment]
Awesome. I'll close it for now
