### ISSUE TITLE
Crash when editing text | Sketch 49.3

### ISSUE THREAD

**Issue by jghightman** [DWilliames/paddy2-beta#3]
Steps

1. Made rectangle shape
2. Added icon from icon library
3. Added text
4. Stacked Text and icon horizontal 8px
5. Grouped all and set padding 4 16 

All good up to here... when I clicked in to edit text, I entered the new text but then when I was done I could not click out of editing the text. Clicking out of it crashed. 

Removed linked icon, didn't crash ... but seems to be still having issues escaping from text edit mode. Can't seem to click out of it. So hitting R would just add onto text. Went to Insert shape > Rectangle .. crashed. 

Was able to repeat. Can send problem report if it will help. Hope this helps! Goodluck and thanks for your efforts on this!

Thx!

**Comment by jghightman** [comment]
Realize I didn't disable Anima .. will do and test this again and report back.

**Comment by DWilliames** [comment]
Thanks @jghightman!

Yeah, a 'problem report' would be extremely helpful. 
Let me know how you go. Thanks :)

**Comment by jghightman** [comment]
Think it might have been Anima. Disabled and having no issues thus far. Closing.
