### ISSUE TITLE
Padding cannot be changed

### ISSUE THREAD

**Issue by aparajita** [DWilliames/paddy2-beta#33]
When I first set a layer to a padding layer, Paddy 2 correctly uses the current padding. The problem occurs if several sides have the same padding. For example, if the left/right padding is the same, subsequent attempts to change the left or right immediately change the other, and there is no way to decouple the two.

Worst is if all of the sides have the same padding. Then changing any side changes all of them!

I'm guessing that internally Paddy 2 is converting something like `10, 12, 7, 12` into `[10 12 7]` and `10, 10, 10, 10` into `[10]`. Then when a number is changed, you update inferred values.

Maybe this is the intended behavior, but the UI doesn't reflect it and it is unexpected. If the layer name does not have a padding spec, then the inspector UI should always be treated as a full `[top right bottom left]` spec, no matter what the numbers are.

**Comment by trvsss** [comment]
Good solution @Dwilliames!

**Comment by godyj** [comment]
Good to know about this secret toggle. I was aware of Sketch's toggle, but glad to see Paddy can leverage it also.

**Comment by DWilliames** [comment]
Please verify it's fixed in v0.5 that just went live.
If it's not fixed for you; then please re-open this issue.
