### ISSUE TITLE
Massive slowdown with 0.4

### ISSUE THREAD

**Issue by aparajita** [DWilliames/paddy2-beta#34]
Sorry to say that although 0.4 fixes a bunch of issues, it is causing massive slowdowns on every layer operation I perform in Sketch. I'm regularly getting the beachball. I can send my file privately if you want to try yourself.

**Comment by aparajita** [comment]
Seems it had nothing to do with Paddy, Sketch was slowing down horribly without it. Sorry for the noise and keep up the great work!

**Comment by godyj** [comment]
Can you please let us know what was causing the issue so we can be aware of the known problem?

**Comment by aparajita** [comment]
Not sure, could be memory issues. After a reboot Sketch was fast again.
