### ISSUE TITLE
can't choose „show properties in layer names“

### ISSUE THREAD

**Issue by Nevu** [DWilliames/paddy2-beta#36]
Hi,

like I said: I can't choose „show properties in layer names“. the checkbox is not clickable.
Sketch 50.02, Paddy 2 0.4.

BR

**Comment by DWilliames** [comment]
Thanks @Nevu.

Yeah, I haven't properly built that feature yet. Rather than removing the checkbox for v0.4, I disabled in the meantime until I fix it. :P 

So right now, you purposefully can't click it. But it will be re-anabled in a future release, when I actually build out the capability 👍
