### ISSUE TITLE
Clicking on “Padding” or ”Stack layers” button doesn’t work

### ISSUE THREAD

**Issue by KevinGutowski** [DWilliames/paddy2-beta#38]
Currently, you have to click the “plus” icon which isn’t the expected behavior. See the gif for the desired click area:

![jun-05-2018 16-07-27](https://user-images.githubusercontent.com/4199296/41007485-ed79c834-68da-11e8-9730-653efb9e29c5.gif)

**Comment by DWilliames** [comment]
Good catch! The label was intercepting the 'mouse up' event.
Is fixed for v0.5 👍

**Comment by DWilliames** [comment]
Please verify it's fixed in v0.5 that just went live.
If it's not fixed for you; then please re-open this issue.
