### ISSUE TITLE
Containers with None Reset on Artboard resize. 

### ISSUE THREAD

**Issue by blaskotron** [DWilliames/paddy2-beta#43]
In this video the container has the right dimension set to **none**. 

When artboard is resized the containers content is resized similar to if the container was set to **zero**. But the content moves and not the container.

![paddynone](https://user-images.githubusercontent.com/2779211/41789938-fd2dba6e-761e-11e8-8529-840acfdbcffc.gif)

**Comment by aparajita** [comment]
Having the actual file to test with would be helpful, please attach it to this issue.

**Comment by blaskotron** [comment]
[Paddy None.sketch.zip](https://github.com/DWilliames/paddy2-beta/files/2133453/Paddy.None.sketch.zip)

**Comment by aparajita** [comment]
Thank you, I'm sure Dave will appreciate it.

**Comment by DWilliames** [comment]
Thanks @aparajita and @blaskotron.
Sorry for the delay. I'm able to reproduce this issue. 
Looking into it now.

**Comment by DWilliames** [comment]
I've fixed this issue now in v0.5 – however there's still quite a few nuances I need to fix when resizing groups that contain Padding layers.

**Comment by DWilliames** [comment]
Please verify it's fixed in v0.5 that just went live.
If it's not fixed for you; then please re-open this issue.
