### ISSUE TITLE
Using None in Symbols Crashes Sketch

### ISSUE THREAD

**Issue by blaskotron** [DWilliames/paddy2-beta#45]
When setting background layer of a symbol to none it slows down sketch or crashes sketch.  Usually a crash. 

Heres the file. 

[Paddy Button Crash.sketch.zip](https://github.com/DWilliames/paddy2-beta/files/2141310/Paddy.Button.Crash.sketch.zip)

**Comment by DWilliames** [comment]
Great catch @blaskotron! Sorry for the delay in getting back; I am able to reproduce this and will look into it now :)

**Comment by DWilliames** [comment]
Fixed it now in v0.5 – coming soon :)

**Comment by DWilliames** [comment]
Please verify it's fixed in v0.5 that just went live.
If it's not fixed for you; then please re-open this issue.
