### ISSUE TITLE
Shortcut for adding a padded rectangle behind selection

### ISSUE THREAD

**Issue by highvoltaged** [DWilliames/paddy2-beta#50]
I love this in paddy 1. When you press imply padding, and it can't find a suitable background shape, it creates a new rectangle.
I hope you consider keeping that in paddy2.

Speaking of which, currently i can't test paddy 2, cause i rely so heavily on the shortucts introduced in the first version.
For me that is THE most useful feautre. Adding or changing spacing on multiple groups is the shit.

Paddy is a life saver for me, i use it from the first second i start a project.
I've gone so deep, that i use a layer called "Wrapper" and stack the whole webpage inside it vertically.
Then i enable "select contents of group" in sketch and i dont have to always double click into multiple groups. If ii want to change the spacing of the elements, i just select one block, press Esc, and that selects the parent group, so i can use the shortcut to change the Spacing.

This way i can just reorder my whole webpage on the fly, i f i want try new layouts. And more iportantly if one section's length changes, paddy will take care of it on the rest of the page.
I HATED always selecting everything and nudging all the time if i just had to resize something 10px on the top of the page.

Big thanks for this tool, and i wait (not so) patiently for the shortcuts in paddy2.
:D

**Comment by DWilliames** [comment]
Thanks for all the feedback @highvoltaged! It's great to hear about how you use it :) 

The shortcuts are coming in v0.5 to be the same as in Paddy 1. I've done them for Stacking; just need to do it for Padding now too :)

**Comment by DWilliames** [comment]
Please verify it's fixed in v0.5 that just went live.
If it's not fixed for you; then please re-open this issue.

**Comment by highvoltaged** [comment]
Thanks for the shortcuts!

I have instantly bumped into a lot of bugs when working projects made with Paddy 1.

At one instance i just selected a symbol and clicked add padding, and it got resized to very small and positioned to the top left corner of the artboard.

I will try to send a project file from work tomorrow if i have time.

Another thing i noticed, that i cannot write letters into the stacking shortcut window.
For example i want to write "20v l"  to have the layers aligned to the left. Currently i can't do that from the shortcut window. It's good to have buttons for horizontal and vertical, but it was super fast the old way, just writing it in.

Or maybe some kind of shortcut like you have brilliantly did on the padding window:
 "command+enter" toggles through the variations.
So it could maybe be like command+L or R 

But the old way was plenty good.

**Comment by highvoltaged** [comment]
Also i have noticed, that working with a paddy 1 file, sometimes the shortcut way doesn't work, sometimes working via the interface doesn't update the positions. But this one needs extensive testing, i have just quickly tried it out. If i find some reproduceable bug i will open an issue.
