### ISSUE TITLE
[Bug] Click and Dragging Elements Inconsistent Behavior in 0.5

### ISSUE THREAD

**Issue by blaskotron** [DWilliames/paddy2-beta#53]
Using mouse to move an object in a stack will often leave it in the dragged position out of stacked position. But using the arrow key USUALLY will put it back in correct stack position. 
![stack with mouse](https://user-images.githubusercontent.com/2779211/43091411-07819302-8e78-11e8-92d8-c2dcde1718fb.gif)
sketch file
[stack with mouse.sketch.zip](https://github.com/DWilliames/paddy2-beta/files/2220288/stack.with.mouse.sketch.zip)

**Comment by aparajita** [comment]
Related to #22

**Comment by blaskotron** [comment]
I don't recall this problem existing before .5

**Comment by DWilliames** [comment]
@blaskotron this does seem new. It did use to snap back... I'll try and investigate it soon. Good find.

It's slightly different to #22 @aparajita — as this isn't snapping back at all, not just maintaining the group position after re-ordering.

**Comment by blaskotron** [comment]
Looks fixed in .6. 

Thank you very much. Great work.

**Comment by DWilliames** [comment]
Awesome. Thanks @blaskotron 👍
