### ISSUE TITLE
Bug: Text alignment changes from "Auto" to "Fixed" when resizing a "Paddy" group

### ISSUE THREAD

**Issue by richardsison** [DWilliames/paddy2-beta#62]
When you have a group with a text box inside that is set to "Auto" alignment (not Fixed), Paddy changes the alignment value to "Fixed".

Demo: https://d.pr/v/bS9TLM

Is this meant to happen?

**Comment by DWilliames** [comment]
Good find again. This is a mix with the issue of #61. I think I need to rework that 'resize' function completely. Cheers 👍

**Comment by DWilliames** [comment]
@richardsison Actually this seems to be the behaviour of Sketch.
If I have Paddy 2 disabled and I put a Text layer with 'fixed width' and 'auto alignment' in a group and resize the group... it appears to set text alignment from 'Auto' to 'Fixed'. So this seems like a Sketch problem, and not sure I will be able to fix this.

**Comment by richardsison** [comment]
Ah nice, feel free to close it good sir.

**Comment by richardsison** [comment]
Oh I just did :P Hope you don't mind…!
