### ISSUE TITLE
Request: Open source the source code for paddy2-beta

### ISSUE THREAD

**Issue by websiddu** [DWilliames/paddy2-beta#78]
Hi David, 
I was wondering if there any plans to open source your source code so other developers could adopt this plugin and may be continue working on this? 

I would love to help here. I have build many complex plugins including websiddu/sketch-material. 

// Sid

**Comment by DWilliames** [comment]
Thanks @websiddu. 

I definitely intend to open source the code — I just need to change a couple of things to make it work within it's own repository. 

I'll try and lock it in within the next couple of days. 👍 
I'll keep you posted.

**Comment by DWilliames** [comment]
Alright @websiddu — I managed to do it!
You can find the source code here: https://github.com/DWilliames/paddy2-beta-source-code

**Comment by modulareverything** [comment]
The man. The legend 👌🏻
