### ISSUE TITLE
Setting padding value to 'x' ?

### ISSUE THREAD

**Issue by highvoltaged** [DWilliames/paddy2-beta#8]
Will there be an option like in Paddy1, to set a padding value to 'x'?
I used that all the time.

**Comment by DWilliames** [comment]
Yeah; there will be. 👍 

The way I'll handle it is to simply enter nothing into that input field. So you won't have to enter 'x' specifically; you'll just have to delete the number instead.

**Comment by richardsison** [comment]
Yeah, I was trying this too… Trying to put "x" in the field just crashed Sketch. Raised an Issue for it (https://github.com/DWilliames/paddy2-beta/issues/18).

I'd still like the ability to set padding via the layer panel though — it was the main reason I chose Paddy over Anima. Crossing my fingers!

**Comment by DWilliames** [comment]
@highvoltaged – just released v0.3 which has this fix. You can either enter a padding value of 'x' or clear the input to 'none'.
